name: 'app'
type: "ruby:2.5"

web:
    upstream:
        socket_family: unix
    commands:
        start: "unicorn -l $SOCKET -E production config.ru"

    locations:
        "/":
            root: "public"
            passthru: true
            expires: 1h
            allow: true

relationships:
    database: "database:mysql"

disk: 2048

hooks:
  build: bundle install --without development test
  deploy: RACK_ENV=production bundle exec rake db:migrate

mounts:
    tmp:
        source: local
        source_path: tmp
    logs:
        source: local
        source_path: logs
