meta_product_name: "Kiosk"
meta_title: "Kiosk - Actualités & ressources  "
meta_description: "Centre de ressources médiatiques de l'Académie de recherche et d'enseignement supérieur (ARES)"
meta_image: "kiosk-thumbnail.png" # should exist in `app/assets/images/`
twitter_account: "@pARESfwb_be"   # required for Twitter Cards
