# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tag.create(name:"conditions d'accès", status: 'published')
Tag.create(name:"alternance", status: 'published')
Tag.create(name:"bibliothèques", status: 'published')
Tag.create(name:"bourses", status: 'published')
Tag.create(name:"coopération au développement", status: 'published')
Tag.create(name:"déchets", status: 'published')
Tag.create(name:"développement durable", status: 'published')
Tag.create(name:"droits d'inscription", status: 'published')
Tag.create(name:"e-paysage", status: 'published')
Tag.create(name:"élections rectorales", status: 'published')
Tag.create(name:"énergie", status: 'published')
Tag.create(name:"engagement - citoyeneté - démocratie", status: 'published')
Tag.create(name:"enseignement privé", status: 'published')
Tag.create(name:"entrepreneuriat", status: 'published')
Tag.create(name:"secteur privé", status: 'published')
Tag.create(name:"environnement", status: 'published')
Tag.create(name:"vie étudiante", status: 'published')
Tag.create(name:"examens", status: 'published')
Tag.create(name:"financement", status: 'published')
Tag.create(name:"finançabilité", status: 'published')
Tag.create(name:"formation continue", status: 'published')
Tag.create(name:"formation initiale des enseignants", status: 'published')
Tag.create(name:"genre", status: 'published')
Tag.create(name:"gouvernance", status: 'published')
Tag.create(name:"enseignement inclusif", status: 'published')
Tag.create(name:"information-orientation", status: 'published')
Tag.create(name:"informatique", status: 'published')
Tag.create(name:"infrastructures", status: 'published')
Tag.create(name:"international", status: 'published')
Tag.create(name:"kinés", status: 'published')
Tag.create(name:"logement", status: 'published')
Tag.create(name:"logopédie", status: 'published')
Tag.create(name:"médecine", status: 'published')
Tag.create(name:"dentisterie", status: 'published')
Tag.create(name:"exmd", status: 'published')
Tag.create(name:"migration", status: 'published')
Tag.create(name:"mobilité étudiante", status: 'published')
Tag.create(name:"non résidents", status: 'published')
Tag.create(name:"numérique", status: 'published')
Tag.create(name:"offre - habilitations", status: 'published')
Tag.create(name:"open data", status: 'published')
Tag.create(name:"pacte d'excellente", status: 'published')
Tag.create(name:"participation étudiante", status: 'published')
Tag.create(name:"paysage - fusions", status: 'published')
Tag.create(name:"pédagogie", status: 'published')
Tag.create(name:"philosophie & citoyenneté", status: 'published')
Tag.create(name:"précarité", status: 'published')
Tag.create(name:"prévention", status: 'published')
Tag.create(name:"recherche", status: 'published')
Tag.create(name:"académiques en danger", status: 'published')
Tag.create(name:"santé", status: 'published')
Tag.create(name:"sécurité", status: 'published')
Tag.create(name:"VAE", status: 'published')
Tag.create(name:"vie pratique", status: 'published')
Tag.create(name:"vie privée", status: 'published')
